api_platform:
    title: 'INVOICING MANAGEMENT'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [2,3]
    
    collection:
        pagination:
            enabled: false
            client_enabled: true
            items_per_page: 5
            client_items_per_page: true
            items_per_page_parameter_name: "count"